-- RUN AS: SYS OR SYSTEM
-- CREATE A NEW USER: DB_AUDIT
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT CREATE TABLE, CREATE TRIGGER, CREATE SEQUENCE, CREATE PROCEDURE TO DB_AUDIT;
GRANT UNLIMITED TABLESPACE TO DB_AUDIT;

-- RUN AS: DB_AUDIT
-- Create a table: DB_AUDIT.CUSTOMERS
CREATE TABLE DB_AUDIT.CUSTOMERS (
    CUSTOMER_ID NUMBER(8) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    CITY VARCHAR2(30),
    STATE VARCHAR2(30),
    PIN_CODE NUMBER(6),
    CTL_INS_DTTM TIMESTAMP,
    CTL_UPD_DTTM TIMESTAMP,
    CTL_UPD_USER VARCHAR2(20),
    CTL_REC_STAT CHAR(1)
);

-- Create a table: DB_AUDIT.CUSTOMERS_HISTORY
CREATE TABLE DB_AUDIT.CUSTOMERS_HISTORY (
    CUSTOMER_ID NUMBER(8) NOT NULL,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    CITY VARCHAR2(30),
    STATE VARCHAR2(30),
    PIN_CODE NUMBER(6),
    CTL_INS_DTTM TIMESTAMP,
    CTL_UPD_DTTM TIMESTAMP,
    CTL_UPD_USER VARCHAR2(20),
    CTL_REC_STAT CHAR(1),
    HST_INS_DTTM TIMESTAMP ,
    HST_OPR_TYPE VARCHAR2(20)
)

-- Create a trigger for audit
CREATE OR REPLACE TRIGGER TRG_CUSTOMERS_AUDIT
BEFORE INSERT OR UPDATE OR DELETE ON DB_AUDIT.CUSTOMERS
FOR EACH ROW
DECLARE
    V_CUSTOMER_ID DB_AUDIT.CUSTOMERS_HISTORY.CUSTOMER_ID%TYPE;
    V_FIRST_NAME DB_AUDIT.CUSTOMERS_HISTORY.FIRST_NAME%TYPE;
    V_LAST_NAME DB_AUDIT.CUSTOMERS_HISTORY.LAST_NAME%TYPE;
    V_CITY DB_AUDIT.CUSTOMERS_HISTORY.CITY%TYPE;
    V_STATE DB_AUDIT.CUSTOMERS_HISTORY.STATE%TYPE;
    V_PIN_CODE DB_AUDIT.CUSTOMERS_HISTORY.PIN_CODE%TYPE;
    V_CTL_INS_DTTM DB_AUDIT.CUSTOMERS_HISTORY.CTL_INS_DTTM%TYPE;
    V_CTL_UPD_DTTM DB_AUDIT.CUSTOMERS_HISTORY.CTL_UPD_DTTM%TYPE;
    V_CTL_UPD_USER DB_AUDIT.CUSTOMERS_HISTORY.CTL_UPD_USER%TYPE;
    V_CTL_REC_STAT DB_AUDIT.CUSTOMERS_HISTORY.CTL_REC_STAT%TYPE;
    V_HST_OPR_TYPE DB_AUDIT.CUSTOMERS_HISTORY.HST_OPR_TYPE%TYPE;
BEGIN
    IF INSERTING THEN
        :NEW.CTL_INS_DTTM := SYSTIMESTAMP;
        :NEW.CTL_UPD_DTTM := NULL;
        :NEW.CTL_REC_STAT := 'A';
        V_HST_OPR_TYPE := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.CTL_UPD_DTTM := SYSTIMESTAMP;
        V_CTL_UPD_DTTM := :NEW.CTL_UPD_DTTM;
        V_HST_OPR_TYPE := 'UPDATE';
    ELSIF DELETING THEN
        V_CUSTOMER_ID := :OLD.CUSTOMER_ID;
        V_FIRST_NAME := :OLD.FIRST_NAME;
        V_LAST_NAME := :OLD.LAST_NAME;
        V_CITY := :OLD.CITY;
        V_STATE := :OLD.STATE;
        V_PIN_CODE := :OLD.PIN_CODE;
        V_CTL_INS_DTTM := :OLD.CTL_INS_DTTM;
        V_CTL_UPD_DTTM := :OLD.CTL_UPD_DTTM;
        V_CTL_UPD_USER := :OLD.CTL_UPD_USER;
        V_CTL_REC_STAT := :OLD.CTL_REC_STAT;
        V_HST_OPR_TYPE := 'DELETE';
    END IF;


    IF INSERTING OR UPDATING THEN
        :NEW.CTL_UPD_USER := USER;
        V_CUSTOMER_ID := :NEW.CUSTOMER_ID;
        V_FIRST_NAME := :NEW.FIRST_NAME;
        V_LAST_NAME := :NEW.LAST_NAME;
        V_CITY := :NEW.CITY;
        V_STATE := :NEW.STATE;
        V_PIN_CODE := :NEW.PIN_CODE;
        V_CTL_INS_DTTM := :NEW.CTL_INS_DTTM;
        V_CTL_UPD_DTTM := :NEW.CTL_UPD_DTTM;
        V_CTL_UPD_USER := :NEW.CTL_UPD_USER;
        V_CTL_REC_STAT := :NEW.CTL_REC_STAT;
    END IF;

    INSERT INTO CUSTOMERS_HISTORY (
        CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        CITY,
        STATE, 
        PIN_CODE,
        CTL_INS_DTTM,
        CTL_UPD_DTTM,
        CTL_UPD_USER,
        CTL_REC_STAT,
        HST_INS_DTTM,
        HST_OPR_TYPE
    ) VALUES (
        V_CUSTOMER_ID,
        V_FIRST_NAME,
        V_LAST_NAME,
        V_CITY,
        V_STATE,
        V_PIN_CODE,
        V_CTL_INS_DTTM,
        V_CTL_UPD_DTTM,
        V_CTL_UPD_USER,
        V_CTL_REC_STAT,
        SYSTIMESTAMP,
        V_HST_OPR_TYPE
    );
EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000, SQLERRM);
END;
/

-- INSERT SOME DATA
INSERT INTO DB_AUDIT.CUSTOMERS(CUSTOMER_ID, FIRST_NAME, LAST_NAME, CITY, STATE, PIN_CODE)
VALUES (1, 'DEVASHISH', 'ROY', 'JAMSHEDPUR', 'JH', 831014);

INSERT INTO DB_AUDIT.CUSTOMERS(CUSTOMER_ID, FIRST_NAME, LAST_NAME, CITY, STATE, PIN_CODE)
VALUES (2, 'PIYUSH', 'KUMAR', 'JAMSHEDPUR', 'JH', 831014);

COMMIT;

-- UPDATE SOME DATA
UPDATE DB_AUDIT.CUSTOMERS 
SET LAST_NAME = 'NEW ROY'
WHERE CUSTOMER_ID = 1; 

COMMIT;

-- DELETE SOME DATA
DELETE FROM DB_AUDIT.CUSTOMERS
WHERE CUSTOMER_ID = 1;

COMMIT;

-- CUSTOMERS TABLE
SELECT * FROM DB_AUDIT.CUSTOMERS;

-- CUSTOMERS_HISTORY TABLE
SELECT * FROM DB_AUDIT.CUSTOMERS_HISTORY;