-- RUN AS: SYS
CREATE USER DB_ERROR IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_ERROR;
GRANT CREATE TABLE, CREATE PROCEDURE TO DB_ERROR;
GRANT UNLIMITED TABLESPACE TO DB_ERROR;

CREATE USER CH8USER IDENTIFIED BY tiger;
GRANT CREATE SESSION TO CH8USER;

-- RUN AS: DB_ERROR
CREATE TABLE DB_ERROR.CUSTOMERS (
    ID NUMBER, 
    NAME VARCHAR2(10),
    CREDIT_LIMIT NUMBER
);

INSERT INTO CUSTOMERS (ID, NAME, CREDIT_LIMIT) 
VALUES(1, 'TOM JONES', 1000);

COMMIT;

CREATE OR REPLACE PROCEDURE DISPLAY_CUSTOMERS AUTHID DEFINER IS
BEGIN
    FOR C IN (SELECT * FROM CUSTOMERS) LOOP
        DBMS_OUTPUT.PUT_LINE(C.ID || ', ' || C.NAME || ', ' || C.CREDIT_LIMIT);
    END LOOP;
END;
/

GRANT EXECUTE ON DISPLAY_CUSTOMERS TO CH8USER;

-- RUN AS: CH8USER
SELECT * FROM DB_ERROR.CUSTOMERS;

EXECUTE DB_ERROR.DISPLAY_CUSTOMERS;