-- RUN AS: SYS
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER, CREATE SEQUENCE, CREATE PROCEDURE TO DB_AUDIT;
GRANT UNLIMITED TABLESPACE TO DB_AUDIT;

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.APP_AUDIT_TABLE (
    TABLE_ID NUMBER PRIMARY KEY,
    TABLE_NAME VARCHAR2(30) NOT NULL,
    TABLE_DESCRIPTION VARCHAR2(200),
    AUDIT_FLAG CHAR(1),
    ARCHIVE_FLAG CHAR(1),
    ARCHIVE_COUNT INTEGER,
    PURGE_FLAG CHAR(1),
    PURGE_COUNT INTEGER,
    COLUMN_NAMES VARCHAR2(4000),
    COLUMN_COUNT INTEGER,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    CTL_INS_DTTM TIMESTAMP,
    CTL_UPD_DTTM TIMESTAMP,
    CTL_UPD_USER VARCHAR2(30),
    CTL_REC_STAT CHAR(1)
);

CREATE TABLE DB_AUDIT.APP_AUDIT_DATA (
    AUDIT_DATA_ID NUMBER PRIMARY KEY,
    TABLE_ID NUMBER REFERENCES DB_AUDIT.APP_AUDIT_TABLE(TABLE_ID),
    AUDIT_DATA CLOB,
    CTL_INS_DTTM TIMESTAMP,
    CTL_UPD_USER VARCHAR2(30),
    CTL_REC_STAT CHAR(1)
);

CREATE SEQUENCE SEQ_APP_AUDIT_DATA
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE DB_AUDIT.DEPARTMENTS (
    DEPARTMENT_ID NUMBER(2) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20),
    CITY VARCHAR2(30),
    STATE CHAR(2)
);

CREATE TABLE DB_AUDIT.EMPLOYEES (
    EMPLOYEE_ID NUMBER(4) PRIMARY KEY,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    JOB_ID NUMBER(2),
    MANAGER_ID NUMBER(4),
    HIRE_DATE TIMESTAMP,
    SALARY NUMBER,
    DEPARTMENT_ID NUMBER(2) REFERENCES DB_AUDIT.DEPARTMENTS(DEPARTMENT_ID)
);

INSERT INTO DB_AUDIT.DEPARTMENTS
VALUES(10, 'ACCOUNTING', 'PISGAH', 'NV');

INSERT INTO DB_AUDIT.DEPARTMENTS
VALUES(11, 'PRODUCTION', 'REDLANDS', 'CA');

INSERT INTO DB_AUDIT.DEPARTMENTS
VALUES(12, 'ENGINEERING', 'DALLAS', 'TX');

COMMIT;

INSERT INTO DB_AUDIT.EMPLOYEES
VALUES(8377, 'DELPHINE', 'WENGER', 54, 26, SYSTIMESTAMP, 102412.44, 10);

INSERT INTO DB_AUDIT.EMPLOYEES
VALUES(2723, 'PASTY', 'GAUDET', 96, 19, SYSTIMESTAMP, 87662.97, 10);

INSERT INTO DB_AUDIT.EMPLOYEES
VALUES(4034, 'MARIO', 'ATWELL', 2, 9, SYSTIMESTAMP, 109001.61, 11);

COMMIT;

CREATE OR REPLACE PACKAGE PKG_APP_AUDIT IS
    PROCEDURE INSERT_DATA(P_TABLE_NAME VARCHAR2, P_COLUMN_VAL CLOB);
    FUNCTION GET_OLD_CLAUSE(P_TABLE_NAME VARCHAR2) RETURN VARCHAR2;
    FUNCTION GET_COL_CLAUSE(P_TABLE_NAME VARCHAR2) RETURN VARCHAR2;
    FUNCTION AUDIT_CHECK(P_TABLE_NAME VARCHAR2) RETURN BOOLEAN;
    FUNCTION PARSE_VALUES(P_STR VARCHAR2) RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_APP_AUDIT
IS
    G_TABLE_ID NUMBER := NULL;
    G_COLUMN_SPEC VARCHAR2(4000) := NULL;

    FUNCTION GET_COL_CLAUSE(P_TABLE_NAME VARCHAR2)
    RETURN VARCHAR2
    IS
        V_TMP VARCHAR2(4000) := NULL;
        V_QUOTES VARCHAR2(3);
        V_CNT NUMBER := 0;
    BEGIN
        SELECT COUNT(*) INTO V_CNT
        FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = UPPER(P_TABLE_NAME)
        ORDER BY COLUMN_ID;

        FOR I IN 1..V_CNT LOOP
            V_TMP := V_TMP || V_QUOTES || ':' || I || V_QUOTES || ' || ''-'' || ';
        END LOOP;

        V_TMP := SUBSTR(V_TMP, 1, LENGTH(V_TMP) - length('||''-''||'));
        RETURN V_TMP;
    END;

    FUNCTION GET_OLD_CLAUSE(P_TABLE_NAME VARCHAR2)
    RETURN VARCHAR2
    IS
        V_REC APP_AUDIT_TABLE%ROWTYPE;
        V_TMP VARCHAR2(4000) := NULL;
        V_START NUMBER := 1;
        V_END NUMBER;
    BEGIN
        FOR I IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = UPPER(P_TABLE_NAME) ORDER BY COLUMN_ID) LOOP
            V_TMP := V_TMP || ':OLD.' || I.COLUMN_NAME || ',';
        END LOOP;

        V_TMP := SUBSTR(V_TMP, 1, LENGTH(V_TMP) - 1);

        RETURN V_TMP;
    END;

    FUNCTION AUDIT_CHECK(P_TABLE_NAME VARCHAR2)
    RETURN BOOLEAN
    IS 
        V_REC APP_AUDIT_TABLE%ROWTYPE;
    BEGIN
        BEGIN
            SELECT * INTO V_REC
            FROM APP_AUDIT_TABLE
            WHERE TABLE_NAME = UPPER(P_TABLE_NAME);
        EXCEPTION
            WHEN OTHERS THEN
                RETURN FALSE;
        END;

        IF(SYSTIMESTAMP <= V_REC.START_DATE OR SYSTIMESTAMP >= V_REC.END_DATE) OR V_REC.AUDIT_FLAG <> 'Y' THEN 
            RETURN FALSE;
        END IF;

        G_TABLE_ID := V_REC.TABLE_ID;
        G_COLUMN_SPEC := V_REC.COLUMN_NAMES;
        RETURN TRUE;
    END;

    FUNCTION PARSE_VALUES(P_STR VARCHAR2)
    RETURN VARCHAR2
    IS 
        V_VAL VARCHAR2(4000) := NULL;
        V_STR VARCHAR2(4000);
        V_POS1 NUMBER;
        V_POS2 NUMBER;
        V_CNT NUMBER := 0;
    BEGIN
        IF G_COLUMN_SPEC IS NULL OR UPPER(G_COLUMN_SPEC) = 'ALL' THEN
            RETURN P_STR;
        END IF;

        V_POS1 := 1;

        LOOP
            V_POS2 := INSTR(P_STR, '-', V_POS1);
            EXIT WHEN V_POS2 = 0;

            V_STR := SUBSTR(P_STR, V_POS1, V_POS2 - V_POS1);
            V_POS1 := V_POS2 + 1;
            V_CNT := V_CNT + 1;

            IF INSTR(G_COLUMN_SPEC, '[' || V_CNT || ']') > 0 THEN
                V_VAL := V_VAL || V_STR || '-';
            END IF;
        END LOOP;

        V_STR := SUBSTR(P_STR, V_POS1);

        RETURN SUBSTR(V_VAL, 1, LENGTH(V_VAL) - 1);
    END;

    PROCEDURE INSERT_DATA (
        P_TABLE_NAME VARCHAR2,
        P_COLUMN_VAL CLOB
    ) IS 
        V_REC DB_AUDIT.APP_AUDIT_TABLE%ROWTYPE;
    BEGIN
        INSERT INTO DB_AUDIT.APP_AUDIT_DATA(AUDIT_DATA_ID, TABLE_ID, AUDIT_DATA, CTL_INS_DTTM, CTL_UPD_USER, CTL_REC_STAT)
        VALUES(SEQ_APP_AUDIT_DATA.NEXTVAL, G_TABLE_ID, P_COLUMN_VAL, SYSTIMESTAMP, USER, 'A');
    END;
END;
/

CREATE OR REPLACE TRIGGER TRG_EMPLOYEES
BEFORE UPDATE OR DELETE ON DB_AUDIT.EMPLOYEES
FOR EACH ROW
DECLARE
    V_TMP CLOB;
    V_FLAG BOOLEAN;
BEGIN
    V_FLAG := PKG_APP_AUDIT.AUDIT_CHECK('EMPLOYEES');
    IF V_FLAG = TRUE THEN
        -- Concatenate values using '-' delimiter
        V_TMP := :OLD.EMPLOYEE_ID || '-' ||
                 :OLD.FIRST_NAME || '-' ||
                 :OLD.LAST_NAME || '-' ||
                 :OLD.JOB_ID || '-' ||
                 :OLD.MANAGER_ID || '-' ||
                 :OLD.HIRE_DATE || '-' ||
                 :OLD.SALARY || '-' ||
                 :OLD.DEPARTMENT_ID;

        -- Optionally, truncate/limit V_TMP to CLOB length if needed
        V_TMP := PKG_APP_AUDIT.PARSE_VALUES(V_TMP);
        PKG_APP_AUDIT.INSERT_DATA('EMPLOYEES', V_TMP);
    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_DEPARTMENTS
BEFORE UPDATE OR DELETE ON DB_AUDIT.DEPARTMENTS
FOR EACH ROW
DECLARE
    V_TMP CLOB;
    V_FLAG BOOLEAN;
BEGIN
    V_FLAG := PKG_APP_AUDIT.AUDIT_CHECK('DEPARTMENTS');
    IF V_FLAG = TRUE THEN
        -- Concatenate OLD values with '-' as a delimiter
        V_TMP := :OLD.DEPARTMENT_ID || '-' ||
                 :OLD.DEPARTMENT_NAME || '-' ||
                 :OLD.CITY || '-' ||
                 :OLD.STATE;

        V_TMP := PKG_APP_AUDIT.PARSE_VALUES(V_TMP);
        PKG_APP_AUDIT.INSERT_DATA('DEPARTMENTS', V_TMP);
    END IF;
END;
/

INSERT INTO DB_AUDIT.APP_AUDIT_TABLE 
VALUES (1, 'EMPLOYEES', 'EMPLOYEE TABLE HOLDING STAFF DATA', 'Y', 'Y', 5, 'Y', 3, '[3][6][7]', 2, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, 'DB_AUDIT', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_TABLE
VALUES (2, 'DEPARTMENTS', 'DEPARTMENT TABLE HOLDING DEPARTMENT DATA', 'Y', 'N', 0, 'N', 0, 'ALL', 3, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, 'DB_AUDIT', 'A');

COMMIT;

-- UPDATE DATA
UPDATE DB_AUDIT.EMPLOYEES 
SET SALARY = 1010
WHERE EMPLOYEE_ID = 8377;

-- DELETE DATA
DELETE FROM DB_AUDIT.DEPARTMENTS
WHERE DEPARTMENT_ID = 12;

COMMIT;

-- APP_AUDIT_DATA
SELECT T.TABLE_NAME, D.AUDIT_DATA, D.CTL_INS_DTTM DATE_CREATED, D.CTL_UPD_USER USERNAME
FROM DB_AUDIT.APP_AUDIT_TABLE T, DB_AUDIT.APP_AUDIT_DATA D
WHERE T.TABLE_ID = D.TABLE_ID;