-- RUN AS: SYS
DROP USER DB_AUDIT CASCADE;
DROP USER SCOTT CASCADE;

CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO DB_AUDIT;
GRANT UNLIMITED TABLESPACE TO DB_AUDIT;

CREATE USER SCOTT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO SCOTT;

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.APP_AUDIT_ENTITY (
    ENTITY_ID NUMBER PRIMARY KEY,
    ENTITY_NAME VARCHAR2(30),
    ENTITY_TYPE VARCHAR2(15),
    CTL_REC_STAT CHAR(1)
);

CREATE TABLE DB_AUDIT.APP_AUDIT_ACTION_TYPE (
    ACTION_TYPE_ID NUMBER PRIMARY KEY,
    ACTION_TYPE_DESC VARCHAR2(30),
    CTL_REC_STAT CHAR(1)
);

CREATE TABLE DB_AUDIT.APP_AUDIT_ACTION (
    AUDIT_ACTION_ID NUMBER PRIMARY KEY,
    AUDIT_START_DATE TIMESTAMP,
    AUDIT_EXPIRE_DATE TIMESTAMP,
    CTL_INS_DTTM TIMESTAMP,
    CTL_UPD_DTTM TIMESTAMP,
    CTL_UPD_USER VARCHAR2(30),
    CTL_REC_STAT CHAR(1),
    ACTION_TYPE_ID NUMBER REFERENCES DB_AUDIT.APP_AUDIT_ACTION_TYPE(ACTION_TYPE_ID),
    ENTITY_ID NUMBER REFERENCES DB_AUDIT.APP_AUDIT_ENTITY(ENTITY_ID)
);

CREATE TABLE DB_AUDIT.APP_AUDIT_DATA (
    AUDIT_DATA_ID NUMBER PRIMARY KEY,
    AUDIT_DATA VARCHAR2(4000),
    AUDIT_ACTION_ID NUMBER REFERENCES DB_AUDIT.APP_AUDIT_ACTION,
    AUD_INS_DTTM TIMESTAMP,
    AUD_UPD_USER VARCHAR2(30),
    AUD_REC_STAT CHAR(1)
);

CREATE SEQUENCE SEQ_APP_AUDIT_DATA 
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE DB_AUDIT.APP_TBL1 (
    CODE NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(20)
);

CREATE TABLE DB_AUDIT.APP_TBL2 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(35),
    PHONE VARCHAR2(14)
);

-- INSERT DATA
INSERT INTO DB_AUDIT.APP_TBL1(CODE, DESCRIPTION)
VALUES(1, 'DESCRIPTION #1');

INSERT INTO DB_AUDIT.APP_TBL1(CODE, DESCRIPTION)
VALUES(2, 'DESCRIPTION #2');

INSERT INTO DB_AUDIT.APP_TBL2(ID, NAME, PHONE)
VALUES(1, 'TOM JONES', '1234567890');

INSERT INTO DB_AUDIT.APP_TBL2(ID, NAME, PHONE)
VALUES(2, 'LINDA EVANS', '2345678901');

INSERT INTO DB_AUDIT.APP_TBL2(ID, NAME, PHONE)
VALUES(3, 'JOAN COLLINS', '3456789012');

COMMIT;

INSERT INTO DB_AUDIT.APP_AUDIT_ACTION_TYPE(ACTION_TYPE_ID, ACTION_TYPE_DESC, CTL_REC_STAT)
VALUES(1, 'INSERT', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_ACTION_TYPE(ACTION_TYPE_ID, ACTION_TYPE_DESC, CTL_REC_STAT)
VALUES(2, 'UPDATE', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_ACTION_TYPE(ACTION_TYPE_ID, ACTION_TYPE_DESC, CTL_REC_STAT)
VALUES(3, 'DELETE', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_ENTITY(ENTITY_ID, ENTITY_NAME, ENTITY_TYPE, CTL_REC_STAT)
VALUES(1, 'SCOTT', 'USER', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_ENTITY(ENTITY_ID, ENTITY_NAME, ENTITY_TYPE, CTL_REC_STAT)
VALUES(2, 'APP_TBL1', 'TABLE', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_ENTITY(ENTITY_ID, ENTITY_NAME, ENTITY_TYPE, CTL_REC_STAT)
VALUES(3, 'APP_TBL2', 'TABLE', 'A');

INSERT INTO DB_AUDIT.APP_AUDIT_ACTION(AUDIT_ACTION_ID, AUDIT_START_DATE, AUDIT_EXPIRE_DATE, CTL_INS_DTTM, CTL_UPD_DTTM, CTL_UPD_USER, CTL_REC_STAT, ACTION_TYPE_ID, ENTITY_ID)
VALUES(1, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, USER, 'A', 1, 1);

-- INSERT INTO DB_AUDIT.APP_AUDIT_ACTION(AUDIT_ACTION_ID, AUDIT_START_DATE, AUDIT_EXPIRE_DATE, CTL_INS_DTTM, CTL_UPD_DTTM, CTL_UPD_USER, CTL_REC_STAT, ACTION_TYPE_ID, ENTITY_ID)
-- VALUES(2, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, USER, 'A', 2, 2);

-- INSERT INTO DB_AUDIT.APP_AUDIT_ACTION(AUDIT_ACTION_ID, AUDIT_START_DATE, AUDIT_EXPIRE_DATE, CTL_INS_DTTM, CTL_UPD_DTTM, CTL_UPD_USER, CTL_REC_STAT, ACTION_TYPE_ID, ENTITY_ID)
-- VALUES(3, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, USER, 'A', 3, 2);

INSERT INTO DB_AUDIT.APP_AUDIT_ACTION(AUDIT_ACTION_ID, AUDIT_START_DATE, AUDIT_EXPIRE_DATE, CTL_INS_DTTM, CTL_UPD_DTTM, CTL_UPD_USER, CTL_REC_STAT, ACTION_TYPE_ID, ENTITY_ID)
VALUES(2, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, USER, 'A', 2, 2);

INSERT INTO DB_AUDIT.APP_AUDIT_ACTION(AUDIT_ACTION_ID, AUDIT_START_DATE, AUDIT_EXPIRE_DATE, CTL_INS_DTTM, CTL_UPD_DTTM, CTL_UPD_USER, CTL_REC_STAT, ACTION_TYPE_ID, ENTITY_ID)
VALUES(3, SYSTIMESTAMP, SYSTIMESTAMP + 99, SYSTIMESTAMP, SYSTIMESTAMP, USER, 'A', 3, 3);

COMMIT;

CREATE OR REPLACE PACKAGE PKG_APP_AUDIT IS
    PROCEDURE INSERT_DATA (
        P_TABLE_NAME VARCHAR2, P_OPERATION VARCHAR2
    );

    FUNCTION AUDIT_CHECK (
        P_USER_NAME VARCHAR2,
        P_TABLE_NAME VARCHAR2,
        P_OPERATION VARCHAR2
    ) RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_APP_AUDIT IS
    FUNCTION AUDIT_CHECK(P_USER_NAME VARCHAR2, P_TABLE_NAME VARCHAR2, P_OPERATION VARCHAR2)
    RETURN NUMBER
    IS
        V_ID NUMBER := 0;
    BEGIN
        BEGIN
            SELECT A.AUDIT_ACTION_ID INTO V_ID
            FROM DB_AUDIT.APP_AUDIT_ENTITY E, DB_AUDIT.APP_AUDIT_ACTION A, DB_AUDIT.APP_AUDIT_ACTION_TYPE T
            WHERE E.ENTITY_TYPE = 'USER' 
            AND E.ENTITY_NAME = P_USER_NAME 
            AND T.ACTION_TYPE_DESC = UPPER(P_OPERATION)
            AND A.ENTITY_ID = E.ENTITY_ID
            AND A.ACTION_TYPE_ID = T.ACTION_TYPE_ID
            AND SYSTIMESTAMP BETWEEN A.AUDIT_START_DATE AND A.AUDIT_EXPIRE_DATE;
        EXCEPTION 
            WHEN OTHERS THEN
                V_ID := NULL;
        END;

        IF V_ID IS NULL THEN
            BEGIN
                SELECT A.AUDIT_ACTION_ID INTO V_ID
                FROM DB_AUDIT.APP_AUDIT_ENTITY E, DB_AUDIT.APP_AUDIT_ACTION_TYPE T, DB_AUDIT.APP_AUDIT_ACTION A
                WHERE E.ENTITY_TYPE = 'TABLE' 
                AND E.ENTITY_NAME = P_TABLE_NAME
                AND T.ACTION_TYPE_DESC = UPPER(P_OPERATION)
                AND A.ENTITY_ID = E.ENTITY_ID
                AND A.ACTION_TYPE_ID = T.ACTION_TYPE_ID
                AND SYSTIMESTAMP BETWEEN A.AUDIT_START_DATE AND A.AUDIT_EXPIRE_DATE;
            EXCEPTION
                WHEN OTHERS THEN
                    RETURN NULL;
            END;
        END IF;

        RETURN V_ID;
    END;

    PROCEDURE INSERT_DATA(P_TABLE_NAME VARCHAR2, P_OPERATION VARCHAR2)
    IS
        V_ID NUMBER;
    BEGIN
        V_ID := AUDIT_CHECK(USER, P_TABLE_NAME, P_OPERATION);
        
        IF V_ID IS NULL THEN
            RETURN;
        END IF;

        INSERT INTO DB_AUDIT.APP_AUDIT_DATA(AUDIT_DATA_ID, AUDIT_DATA, AUDIT_ACTION_ID, AUD_INS_DTTM, AUD_UPD_USER, AUD_REC_STAT)
        VALUES(SEQ_APP_AUDIT_DATA.NEXTVAL, P_OPERATION, V_ID, SYSTIMESTAMP, USER, 'A');
    END;
END;
/

CREATE OR REPLACE TRIGGER TRG_APP_TBL1
BEFORE INSERT OR UPDATE OR DELETE
ON DB_AUDIT.APP_TBL1
FOR EACH ROW
DECLARE
    V_OPERATION VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        V_OPERATION := 'INSERT';
    ELSIF UPDATING THEN
        V_OPERATION := 'UPDATE';
    ELSE
        V_OPERATION := 'DELETE';
    END IF;

    PKG_APP_AUDIT.INSERT_DATA('APP_TBL1', V_OPERATION);
END;
/

CREATE OR REPLACE TRIGGER TRG_APP_TBL2
BEFORE INSERT OR UPDATE OR DELETE
ON DB_AUDIT.APP_TBL2
FOR EACH ROW
DECLARE
    V_OPERATION VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        V_OPERATION := 'INSERT';
    ELSIF UPDATING THEN
        V_OPERATION := 'UPDATE';
    ELSE
        V_OPERATION := 'DELETE';
    END IF;

    PKG_APP_AUDIT.INSERT_DATA('APP_TBL2', V_OPERATION);
END;
/

-- GRANT INSERT, UPDATE AND DELTE TO SCOTT
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_AUDIT.APP_TBL1 TO SCOTT;
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_AUDIT.APP_TBL2 TO SCOTT;

-- TESTING TIME
-- INSERT SOME DATA
INSERT INTO DB_AUDIT.APP_TBL1
VALUES(3, 'DESCRIPTION #3');

INSERT INTO DB_AUDIT.APP_TBL2
VALUES(4, 'PIYUSH KUMAR', '9876543210');

COMMIT;

-- UPDATE SOME DATA
UPDATE DB_AUDIT.APP_TBL1
SET DESCRIPTION = 'NEW DESCRIPTION #1'
WHERE CODE = 1;

UPDATE DB_AUDIT.APP_TBL1
SET DESCRIPTION = 'NEW DESCRIPTION #2'
WHERE CODE = 2;

UPDATE DB_AUDIT.APP_TBL2
SET PHONE = '9876543210'
WHERE ID = 1;

-- DELETE SOME DATA
DELETE FROM DB_AUDIT.APP_TBL2
WHERE ID = 1;

DELETE FROM DB_AUDIT.APP_TBL2
WHERE ID = 2;

COMMIT;

-- APP_AUDIT_DATA
SELECT * FROM DB_AUDIT.APP_TBL1;
SELECT * FROM DB_AUDIT.APP_TBL2;

SELECT * FROM DB_AUDIT.APP_AUDIT_ENTITY;
SELECT * FROM DB_AUDIT.APP_AUDIT_ACTION_TYPE;
SELECT * FROM DB_AUDIT.APP_AUDIT_ACTION;
SELECT * FROM DB_AUDIT.APP_AUDIT_DATA;