-- RUN AS: SYS
-- Create user: DB_AUDIT
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT ALL PRIVILEGES TO DB_AUDIT;

GRANT SELECT ON V_$SQL TO DB_AUDIT;
GRANT SELECT ON V_$SESSION TO DB_AUDIT;

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.APP_AUDIT_SQLS (
    TABLE_NAME VARCHAR2(30) NOT NULL,
    SQL_STATEMENT VARCHAR2(4000) NOT NULL,
    SQL_TYPE VARCHAR2(10) NOT NULL,
    CTL_INS_DTTM TIMESTAMP,
    CTL_INS_USER VARCHAR2(30),
    CTL_OPS_USER VARCHAR2(30),
    CTL_IP_ADDR VARCHAR2(255)
);

CREATE TABLE DB_AUDIT.CUSTOMERS (
    ID NUMBER,
    NAME VARCHAR2(10),
    CREDIT_LIMIT NUMBER
);

INSERT INTO DB_AUDIT.CUSTOMERS
VALUES(1, 'TOM JONES', 2);

INSERT INTO DB_AUDIT.CUSTOMERS
VALUES(2, 'BLA AFENDI', 500);

COMMIT;

CREATE OR REPLACE TRIGGER TRG_CUSTOMER_BDIUR
BEFORE INSERT OR UPDATE OR DELETE
ON DB_AUDIT.CUSTOMERS
FOR EACH ROW
DECLARE
    V_STMT VARCHAR2(4000);
    V_OPER VARCHAR2(10);
    V_SESSION_ID NUMBER;
    V_IP_ADDRESS VARCHAR2(255);
    V_OS_USER VARCHAR2(255);
    V_CURRENT_USERID NUMBER;
BEGIN
    IF INSERTING THEN
        V_OPER := 'INSERT';
    ELSIF UPDATING THEN
        V_OPER := 'UPDATE';
    ELSE
        V_OPER := 'DELETE';
    END IF;

    SELECT SYS_CONTEXT('USERENV', 'SESSIONID') INTO V_SESSION_ID FROM DUAL;
    SELECT SYS_CONTEXT('USERENV', 'IP_ADDRESS') INTO V_IP_ADDRESS FROM DUAL;
    SELECT SYS_CONTEXT('USERENV', 'OS_USER') INTO V_OS_USER FROM DUAL;
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_USERID') INTO V_CURRENT_USERID FROM DUAL;

    SELECT Q.SQL_TEXT INTO V_STMT
    FROM 
        V$SQL Q, V$SESSION S
    WHERE
        S.AUDSID = V_SESSION_ID
        AND Q.PARSING_USER_ID = V_CURRENT_USERID
        AND Q.LAST_LOAD_TIME = (
                SELECT MAX(LAST_LOAD_TIME) 
                FROM V$SQL 
                WHERE 
                    PARSING_USER_ID = Q.PARSING_SCHEMA_ID 
                    AND UPPER(SQL_TEXT) LIKE '%' || V_OPER || '%' 
                    AND UPPER(SQL_TEXT) NOT LIKE 'SELECT' || '%'
            )
        AND UPPER(Q.SQL_TEXT) NOT LIKE 'SELECT' || '%'
        AND UPPER(Q.SQL_TEXT) LIKE '%' || V_OPER || '%';
    
    INSERT INTO DB_AUDIT.APP_AUDIT_SQLS(TABLE_NAME, SQL_STATEMENT, SQL_TYPE, CTL_INS_DTTM, CTL_INS_USER, CTL_OPS_USER, CTL_IP_ADDR)
    VALUES('CUSTOMERS', V_STMT, V_OPER, SYSTIMESTAMP, USER, V_OS_USER, V_IP_ADDRESS);
END;
/


-- RUN AS: DB_AUDIT
-- Update the table
UPDATE DB_AUDIT.CUSTOMERS
SET CREDIT_LIMIT = 1000
WHERE ID = 1
/

COMMIT;

-- View the audit
SELECT *
FROM DB_AUDIT.APP_AUDIT_SQLS;

-- Drop the trigger
DROP TRIGGER TRG_CUSTOMER_BDIUR;