-- RUN AS: SYS
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT ALL PRIVILEGES TO DB_AUDIT;

AUDIT ALL BY DB_AUDIT;

DELETE SYS.AUD$
/

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.NEW_TEMP (
    NUM NUMBER
);

-- RUN AS: SYS
SELECT * FROM DBA_AUDIT_TRAIL;