-- RUN AS: SYS
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT ALL PRIVILEGES TO DB_AUDIT;

CREATE USER DB_TEST IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_TEST;

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.TEMP (
    NUM NUMBER
);

INSERT INTO DB_AUDIT.TEMP
VALUES(1000);

SELECT * FROM DB_AUDIT.TEMP;

COMMIT;

-- RUN AS: SYS
DELETE SYS.AUD$
/

COMMIT;

AUDIT GRANT ON DB_AUDIT.TEMP;

-- RUN AS: DB_AUDIT
GRANT SELECT ON DB_AUDIT.TEMP TO DB_TEST;

GRANT UPDATE ON DB_AUDIT.TEMP TO DB_TEST;

-- RUN AS: SYS
SELECT * FROM DBA_AUDIT_TRAIL;