-- RUN AS: SYS
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT ALL PRIVILEGES TO DB_AUDIT;

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.CUSTOMER (
    ID NUMBER,
    NAME VARCHAR2(20),
    CR_LIMIT NUMBER
);

INSERT INTO DB_AUDIT.CUSTOMER
VALUES(1, 'TOM', 200);

INSERT INTO DB_AUDIT.CUSTOMER
VALUES(2, 'SUSAN', 130);

INSERT INTO DB_AUDIT.CUSTOMER
VALUES(3, 'LINDA', 230);

COMMIT;

-- RUN AS: SYS

-- Check if the audit is enabled
SHOW PARAMETER audit_trail;

-- If the VALUE is None
-- Edit the VALUE with service as service name ORCLCDB
ALTER SYSTEM SET audit_trail=DB SCOPE=SPFILE;

AUDIT ALTER ON DB_AUDIT.CUSTOMER BY ACCESS WHENEVER SUCCESSFUL;

AUDIT DELETE ON DB_AUDIT.CUSTOMER BY ACCESS WHENEVER SUCCESSFUL;

SELECT * FROM DBA_OBJ_AUDIT_OPTS WHERE OBJECT_NAME = 'CUSTOMER';

-- RUN AS: DB_AUDIT
DELETE FROM DB_AUDIT.CUSTOMER WHERE ID = 2;

ALTER TABLE DB_AUDIT.CUSTOMER
MODIFY NAME VARCHAR2(30);

COMMIT;

-- RUN AS: SYS
SELECT * FROM DBA_AUDIT_TRAIL;