-- RUN AS: SYS
CREATE USER DB_AUDIT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_AUDIT;
GRANT ALL PRIVILEGES TO DB_AUDIT;

AUDIT TABLE BY DB_AUDIT;

-- RUN AS: DB_AUDIT
CREATE TABLE DB_AUDIT.TEMP (
    NUM NUMBER
);

INSERT INTO DB_AUDIT.TEMP
VALUES(1000);

SELECT * FROM DB_AUDIT.TEMP;

DROP TABLE DB_AUDIT.TEMP;

COMMIT;

-- RUN AS: SYS
SELECT * FROM DBA_AUDIT_TRAIL;

-- Disable the audit
NOAUDIT TABLE BY DB_AUDIT;