-- RUN AS: SYS
CREATE OR REPLACE TRIGGER TRG_BEFORE_ALTER
BEFORE ALTER
ON DATABASE
BEGIN
    IF USER = 'DB_AUDIT' THEN
        RAISE_APPLICATION_ERROR(-20000, 'YOU MAY NOT MODIFY STRUCTURE OF ANY TABLE.');
    END IF;
END;

-- RUN AS: DB_VPD
SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
MODIFY FIRST_NAME VARCHAR2(300);

-- RUN AS: SYS
-- Drop the trigger for conflict
DROP TRIGGER TRG_BEFORE_ALTER;