-- RUN AS: SYS
-- Create table: APP_AUDIT_LOGINS
CREATE TABLE APP_AUDIT_LOGINS (
    LOGINS_ID NUMBER,
    SESSION_ID NUMBER,
    USERNAME VARCHAR2(30),
    LOGON_TIME TIMESTAMP,
    LOGOFF_TIME TIMESTAMP,
    IP_ADDRESS VARCHAR2(255),
    AUD_INS_DTTM TIMESTAMP,
    AUD_UPD_DTTM TIMESTAMP,
    AUD_REC_STAT CHAR(1) DEFAULT 'F'
)
/

-- Create a sequence: SEQ_LOGIN_ID for table: APP_AUDIT_LOGINS
CREATE SEQUENCE SEQ_LOGIN_ID
/

-- Create trigger for after LOGON event
CREATE OR REPLACE TRIGGER TRG_AFTER_LOGON
AFTER LOGON
ON DATABASE
DECLARE
    V_SESSION_ID NUMBER;
    V_IP_ADDRESS VARCHAR2(255);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSIONID') INTO V_SESSION_ID FROM DUAL;
    SELECT SYS_CONTEXT('USERENV', 'IP_ADDRESS') INTO V_IP_ADDRESS FROM DUAL;

    INSERT INTO SYS.APP_AUDIT_LOGINS
    VALUES(
        SEQ_LOGIN_ID.NEXTVAL, 
        V_SESSION_ID, 
        USER, 
        SYSTIMESTAMP, 
        NULL, 
        V_IP_ADDRESS, 
        SYSTIMESTAMP, 
        NULL,
        'F'
    );
END;
/

-- Create trigger for before LOGOFF event
CREATE OR REPLACE TRIGGER TRG_BEFORE_LOGOFF
BEFORE LOGOFF
ON DATABASE
DECLARE
    V_SESSION_ID NUMBER;
    V_ID NUMBER;
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'SESSIONID') INTO V_SESSION_ID FROM DUAL;
    
    UPDATE SYS.APP_AUDIT_LOGINS
    SET 
        LOGOFF_TIME = SYSTIMESTAMP,
        AUD_UPD_DTTM = SYSTIMESTAMP,
        AUD_REC_STAT = 'T'
    WHERE 
        SESSION_ID = V_SESSION_ID
        AND USERNAME = USER 
        AND AUD_REC_STAT = 'F';
END;
/

-- Login as different users and logout after some time.

-- RUN AS: SYS
-- View the LOGON and LOGOFF events
SELECT * FROM APP_AUDIT_LOGINS;

-- Drop all the triggers
DROP TRIGGER TRG_AFTER_LOGON;
DROP TRIGGER TRG_BEFORE_LOGOFF;