-- RUN AS: SYS
DROP ROLE CLERK_ROLE;
DROP ROLE MANAGER_ROLE;
DROP ROLE ADMIN_ROLE;

DROP USER DB_VPD CASCADE;
DROP USER DB_VPD_CLERK1 CASCADE;
DROP USER DB_VPD_CLERK2 CASCADE;
DROP USER DB_VPD_CLERK3 CASCADE;