-- RUN AS: SYS
-- Create the required users
CREATE USER DB_VPD IDENTIFIED BY tiger
/

GRANT CREATE SESSION TO DB_VPD
/

GRANT ALL PRIVILEGES TO DB_VPD
/

GRANT EXECUTE ON DBMS_RLS TO DB_VPD
/

-- RUN AS: DB_VPD
-- Create table: DB_VPD.CUSTOMERS
CREATE TABLE DB_VPD.CUSTOMERS(
    SALES_REP_ID NUMBER(4),
    CUSTOMER_ID NUMBER(8),
    CUSTOMER_SSN VARCHAR2(9),
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    ADDR_LINE VARCHAR2(80),
    CITY VARCHAR2(30),
    STATE VARCHAR2(30),
    ZIP_CODE VARCHAR2(9),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(80),
    CC_NUMBER VARCHAR2(20),
    CREDIT_LIMIT NUMBER,
    GENDER CHAR(1),
    STATUS CHAR(1),
    COMMENTS VARCHAR2(1024),
    CTL_UPD_DTTM DATE,
    CTL_UPD_USER VARCHAR2(30),
    CTL_REC_STAT CHAR(1)
);

-- Script to populate table: DB_VPD.CUSTOMERS with 100 rows
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO DB_VPD.CUSTOMERS (
            SALES_REP_ID, CUSTOMER_ID, CUSTOMER_SSN, FIRST_NAME, LAST_NAME, ADDR_LINE, CITY, STATE, ZIP_CODE, PHONE, EMAIL, CC_NUMBER, CREDIT_LIMIT, GENDER, STATUS, COMMENTS, CTL_UPD_DTTM, CTL_UPD_USER, CTL_REC_STAT
        ) VALUES (
            CASE MOD(i, 8) 
                WHEN 0 THEN 2200 
                WHEN 1 THEN 2336 
                WHEN 2 THEN 4587 
                WHEN 3 THEN 4710 
                WHEN 4 THEN 5605 
                WHEN 5 THEN 6415 
                WHEN 6 THEN 7719 
                ELSE 9644 
            END,
            i,
            LPAD(ROUND(DBMS_RANDOM.VALUE(100000000, 999999999)), 9, '0'),
            DBMS_RANDOM.STRING('U', 10),
            DBMS_RANDOM.STRING('U', 10),
            DBMS_RANDOM.STRING('U', 20) || ' Street',
            DBMS_RANDOM.STRING('U', 10),
            DBMS_RANDOM.STRING('U', 10),
            LPAD(ROUND(DBMS_RANDOM.VALUE(10000, 99999)), 9, '0'),
            '555-' || TO_CHAR(ROUND(DBMS_RANDOM.VALUE(100, 999))) || '-' || TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1000, 9999))),
            DBMS_RANDOM.STRING('U', 10) || '@example.com',
            LPAD(ROUND(DBMS_RANDOM.VALUE(4000000000000000, 4999999999999999)), 16, '0'),
            ROUND(DBMS_RANDOM.VALUE(1000, 50000)),
            CASE WHEN MOD(i, 2) = 0 THEN 'M' ELSE 'F' END,
            CASE WHEN MOD(i, 3) = 0 THEN 'A' ELSE 'I' END,
            DBMS_RANDOM.STRING('U', 50),
            SYSDATE - DBMS_RANDOM.VALUE(0, 1000),
            CASE MOD(i, 3) 
                WHEN 0 THEN 'DB_VPD_CLERK1' 
                WHEN 1 THEN 'DB_VPD_CLERK2' 
                ELSE 'DB_VPD_CLERK3' 
            END,
            TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1, 5)))
        );
    END LOOP;
    COMMIT;
END;
/

-- View the data of table: DB_VPD.CUSTOMERS
SELECT * FROM DB_VPD.CUSTOMERS;
/

-- USED FOR SCENARIO #1
SELECT CTL_UPD_USER, COUNT (*)
FROM DB_VPD.CUSTOMERS
GROUP BY CTL_UPD_USER
/

-- USED FOR SCENARIO #2
SELECT SALES_REP_ID, COUNT (*)
FROM DB_VPD.CUSTOMERS
GROUP BY SALES_REP_ID
/

-- USED FOR SCENARIO #3
SELECT CTL_REC_STAT, COUNT(*)
FROM DB_VPD.CUSTOMERS
GROUP BY CTL_REC_STAT
/

-- Create user: VPD_CLERK1 and grant CREATE SESSION to connect to DB
CREATE USER DB_VPD_CLERK1 IDENTIFIED BY tiger
/
GRANT CREATE SESSION TO DB_VPD_CLERK1
/

-- Create user: VPD_CLERK2 and grant CREATE SESSION to connect to DB
CREATE USER DB_VPD_CLERK2 IDENTIFIED BY tiger
/
GRANT CREATE SESSION TO DB_VPD_CLERK2
/

-- Create user: VPD_CLERK3 and grant CREATE SESSION to connect to DB
CREATE USER DB_VPD_CLERK3 IDENTIFIED BY tiger
/
GRANT CREATE SESSION TO DB_VPD_CLERK3
/

-- Grant SELECT, INSERT, UPDATE and DELETE privileges to user: VPD_CLERK1, VPD_CLERK2, VPD_CLERK3 
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_VPD.CUSTOMERS TO DB_VPD_CLERK1
/

GRANT SELECT, INSERT, UPDATE, DELETE ON DB_VPD.CUSTOMERS TO DB_VPD_CLERK2
/

GRANT SELECT, INSERT, UPDATE, DELETE ON DB_VPD.CUSTOMERS TO DB_VPD_CLERK3
/