-- Scenario 3
-- RUN AS: SYS
-- Create the required roles and grant them to users
CREATE ROLE CLERK_ROLE
/

CREATE ROLE MANAGER_ROLE
/

CREATE ROLE ADMIN_ROLE
/

GRANT CLERK_ROLE TO DB_VPD_CLERK1
/

GRANT MANAGER_ROLE TO DB_VPD_CLERK2
/

GRANT ADMIN_ROLE TO DB_VPD_CLERK3
/

-- Grant SELECT privilege on DBA_ROLE_PRIVS to user: DB_VPD
GRANT SELECT ON DBA_ROLE_PRIVS TO DB_VPD
/

-- RUN AS: DB_VPD
-- Create context: DB_VPD_ROLE_SECURITY_LEVEL
CREATE OR REPLACE CONTEXT DB_VPD_ROLE_SECURITY_LEVEL
    USING PKG_DB_VPD_ROLE_SECURITY_LEVEL
/

-- Create package: PKG_DB_VPD_ROLE_SECURITY_LEVEL
CREATE OR REPLACE PACKAGE PKG_DB_VPD_ROLE_SECURITY_LEVEL IS
    PROCEDURE SET_CONTEXT(P_ROLE VARCHAR2 DEFAULT NULL);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_DB_VPD_ROLE_SECURITY_LEVEL IS
    PROCEDURE SET_CONTEXT(P_ROLE VARCHAR2 DEFAULT NULL) IS
    V_USER VARCHAR2(30);
    V_ROLE VARCHAR2(30);
    V_LEVEL NUMBER;
BEGIN
    V_USER := USER;
    V_ROLE := P_ROLE;

    IF P_ROLE IS NULL THEN
        SELECT GRANTED_ROLE
        INTO V_ROLE
        FROM DBA_ROLE_PRIVS
        WHERE GRANTEE = V_USER;
    END IF;

    IF V_ROLE = 'CLERK_ROLE' THEN
        V_LEVEL := 2;
    ELSIF V_ROLE = 'MANAGER_ROLE' THEN
        V_LEVEL := 3;
    ELSIF V_ROLE = 'ADMIN_ROLE' THEN
        V_LEVEL := 4;
    ELSE
        V_LEVEL := 0;
    END IF;

    DBMS_SESSION.SET_CONTEXT('DB_VPD_ROLE_SECURITY_LEVEL', 'SECURITY_LEVEL', V_LEVEL);

    EXCEPTION WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        RETURN;
    END;
END;
/

-- Grant EXECUTE privilege on PKG_DB_VPD_ROLE_SECURITY_LEVEL to user: DB_VPD_CLERK1, DB_VPD_CLERK2, DB_VPD_CLERK3
GRANT EXECUTE ON PKG_DB_VPD_ROLE_SECURITY_LEVEL TO DB_VPD_CLERK1, DB_VPD_CLERK2, DB_VPD_CLERK3
/

-- Create a VPD function policy to implement RLS (row level security)
CREATE OR REPLACE FUNCTION DB_VPD_ROLE_SECURITY_LEVEL(
    P_SCHEMA_NAME IN VARCHAR2, 
    P_OBJECT_NAME IN VARCHAR2
) RETURN VARCHAR2 IS V_WHERE VARCHAR2(4000);
BEGIN
    V_WHERE := 'TO_NUMBER(CTL_REC_STAT) <= ' || nvl(SYS_CONTEXT('DB_VPD_ROLE_SECURITY_LEVEL', 'SECURITY_LEVEL'), 0);
    RETURN V_WHERE;
END;
/

-- Add policy
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA    => 'DB_VPD',
        OBJECT_NAME      => 'CUSTOMERS',
        POLICY_NAME      => 'DB_VPD_ROLE_SECURITY_POLICY',
        FUNCTION_SCHEMA  => 'DB_VPD',
        POLICY_FUNCTION  => 'DB_VPD_ROLE_SECURITY_LEVEL',
        STATEMENT_TYPES  => 'SELECT, UPDATE, DELETE',
        ENABLE           => TRUE
    );
END;
/

-- RUN AS: DB_VPD_CLERK1, DB_VPD_CLERK2, DB_VPD_CLERK3
-- Before setting the context
SELECT SYS_CONTEXT('DB_VPD_ROLE_SECURITY_LEVEL', 'SECURITY_LEVEL')
FROM DUAL 
/

SELECT COUNT(*) FROM DB_VPD.CUSTOMERS
/

-- After setting the context
BEGIN
    DB_VPD.PKG_DB_VPD_ROLE_SECURITY_LEVEL.SET_CONTEXT;
END;

SELECT SYS_CONTEXT('DB_VPD_ROLE_SECURITY_LEVEL', 'SECURITY_LEVEL')
FROM DUAL 
/

SELECT COUNT(*) FROM DB_VPD.CUSTOMERS
/

-- RUN AS: DB_VPD
-- Disable the policy
BEGIN
    DBMS_RLS.ENABLE_POLICY(
        OBJECT_SCHEMA => 'DB_VPD',
        OBJECT_NAME => 'CUSTOMERS',
        POLICY_NAME => 'DB_VPD_ROLE_SECURITY_POLICY',
        ENABLE => TRUE
    );
END;