-- Scenario 2
-- RUN AS: DB_VPD
-- Create table: DB_VPD.CUSTOMERS_APP_CONTEXT
CREATE TABLE DB_VPD.CUSTOMERS_APP_CONTEXT (
    SALES_REP_ID NUMBER,
    USER_NAME VARCHAR2(30)
)
/

-- Grant SELECT privilege on table: DB_VPD.CUSTOMERS_APP_CONTEXT to user: DB_VPD_CLERK1, DB_VPD_CLERK2, DB_VPD_CLERK3
GRANT SELECT ON DB_VPD.CUSTOMERS_APP_CONTEXT TO DB_VPD_CLERK1, DB_VPD_CLERK2, DB_VPD_CLERK3
/

-- Insert data into table: DB_VPD.CUSTOMERS_APP_CONTEXT
INSERT INTO DB_VPD.CUSTOMERS_APP_CONTEXT (SALES_REP_ID, USER_NAME)
VALUES (2336, 'DB_VPD_CLERK1');

INSERT INTO DB_VPD.CUSTOMERS_APP_CONTEXT (SALES_REP_ID, USER_NAME)
VALUES (9644, 'DB_VPD_CLERK2');

INSERT INTO DB_VPD.CUSTOMERS_APP_CONTEXT (SALES_REP_ID, USER_NAME)
VALUES (4587, 'DB_VPD_CLERK3');

COMMIT;

-- RUN AS: SYS
-- Create a package: PKG_DB_VPD_CUST_SALES_REP
CREATE OR REPLACE PACKAGE PKG_DB_VPD_CUST_SALES_REP AS
    PROCEDURE SET_CONTEXT;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_DB_VPD_CUST_SALES_REP IS
    PROCEDURE SET_CONTEXT IS
        V_SALES_REP_ID NUMBER;
    BEGIN
        -- Ensure we fetch the correct SALES_REP_ID
        SELECT SALES_REP_ID
        INTO V_SALES_REP_ID
        FROM DB_VPD.CUSTOMERS_APP_CONTEXT
        WHERE UPPER(USER_NAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));

        -- Set the application context
        DBMS_SESSION.SET_CONTEXT('DB_VPD_CUSTOMERS_SALESREP', 'SALES_REPID', V_SALES_REP_ID);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- If no match, set NULL (which will trigger '1=1' in the policy function)
            DBMS_SESSION.SET_CONTEXT('DB_VPD_CUSTOMERS_SALESREP', 'SALES_REPID', NULL);
    END;
END;
/

-- Create a context: DB_VPD_CUSTOMERS_SALESREP
CREATE OR REPLACE CONTEXT DB_VPD_CUSTOMERS_SALESREP
    USING PKG_DB_VPD_CUST_SALES_REP
/

-- Create a trigger for after LOGON to set context
CREATE OR REPLACE TRIGGER TGR_AFTER_LOGON
AFTER LOGON 
ON DATABASE
BEGIN
    PKG_DB_VPD_CUST_SALES_REP.SET_CONTEXT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- RUN AS: DB_VPD
-- Create a VPD function policy to add a WHERE clause predicate
CREATE OR REPLACE FUNCTION DB_VPD_CUST_SALESREP_WHERE(
    P_SCHEMA_NAME IN VARCHAR2, 
    P_OBJECT_NAME IN VARCHAR2
) RETURN VARCHAR2 IS 
    V_SALES_REP_ID VARCHAR2(30);
BEGIN
    V_SALES_REP_ID := SYS_CONTEXT('DB_VPD_CUSTOMERS_SALESREP', 'SALES_REPID');

    IF V_SALES_REP_ID IS NULL THEN
        RETURN 'SALES_REP_ID = NULL';
    ELSE
        RETURN 'SALES_REP_ID = ' || V_SALES_REP_ID;
    END IF;
END;
/

-- Add a policy
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'DB_VPD',
        OBJECT_NAME => 'CUSTOMERS',
        POLICY_NAME => 'DB_VPD_CUST_SALESREP_POLICY',
        FUNCTION_SCHEMA => 'DB_VPD',
        POLICY_FUNCTION => 'DB_VPD_CUST_SALESREP_WHERE',
        STATEMENT_TYPES => 'SELECT, UPDATE, DELETE',
        ENABLE => TRUE
    );
END;
/

-- RUN AS: DB_VPD_CLERK1, DB_VPD_CLERK2, DB_VPD_CLERK3
SELECT SYS_CONTEXT('DB_VPD_CUSTOMERS_SALESREP', 'SALES_REPID') SALES_REPID FROM DUAL;

SELECT COUNT(*) FROM DB_VPD.CUSTOMERS;

-- RUN AS: DB_VPD
-- Disable policy
BEGIN
    DBMS_RLS.ENABLE_POLICY(
        OBJECT_SCHEMA => 'DB_VPD',
        OBJECT_NAME => 'CUSTOMERS',
        POLICY_NAME => 'DB_VPD_CUST_SALESREP_POLICY',
        ENABLE => FALSE
    );
END;

-- RUN AS: SYS
-- Remove the after LOGON trigger
DROP TRIGGER TGR_AFTER_LOGON;