-- RUN AS: DB_VPD_CLERK2
BEGIN
    DB_VPD.PKG_DB_VPD_ROLE_SECURITY_LEVEL.SET_CONTEXT;
END;

SELECT FIRST_NAME, LAST_NAME, PHONE, EMAIL 
FROM DB_VPD.CUSTOMERS
WHERE ROWNUM < 6;

-- RUN AS: DB_VPD
-- Remove policy
BEGIN 
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'DB_VPD',
        OBJECT_NAME => 'CUSTOMERS',
        POLICY_NAME => 'DB_VPD_ROLE_SECURITY_POLICY'
    );
END;

-- Add policy
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'DB_VPD',
        OBJECT_NAME => 'CUSTOMERS',
        POLICY_NAME => 'DB_VPD_ROLE_SECURITY_POLICY',
        FUNCTION_SCHEMA => 'DB_VPD',
        POLICY_FUNCTION => 'DB_VPD_ROLE_SECURITY_LEVEL',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS => 'PHONE, EMAIL',
        POLICY_TYPE => DBMS_RLS.CONTEXT_SENSITIVE,
        SEC_RELEVANT_COLS_OPT => DBMS_RLS.ALL_ROWS,
        ENABLE => TRUE
    );
END;

-- RUN AS: VPD_CLERK2
BEGIN
    DB_VPD.PKG_DB_VPD_ROLE_SECURITY_LEVEL.SET_CONTEXT;
END;
/

SELECT FIRST_NAME, LAST_NAME, PHONE, EMAIL 
FROM DB_VPD.CUSTOMERS
WHERE ROWNUM < 6;

-- RUN AS: DB_VPD
-- Disable policy
BEGIN
    DBMS_RLS.ENABLE_POLICY(
        OBJECT_SCHEMA => 'DB_VPD',
        OBJECT_NAME => 'CUSTOMERS',
        POLICY_NAME => 'DB_VPD_ROLE_SECURITY_POLICY',
        ENABLE => FALSE
    );
END;