-- SYS CONTEXT
SELECT SYS_CONTEXT('USERENV', 'IP_ADDRESS') FROM DUAL
/

SELECT SYS_CONTEXT('USERENV', 'HOST') FROM DUAL
/

SELECT SYS_CONTEXT('USERENV', 'CURRENT_USER') FROM DUAL
/

SELECT SYS_CONTEXT('USERENV', 'DB_NAME') FROM DUAL
/

DESC DBMS_SESSION;

-- RUN AS: SYS
-- Create the required users
CREATE USER DB_VPD IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_VPD;
GRANT ALL PRIVILEGES TO DB_VPD;

CREATE USER DB_VPD_HR IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_VPD_HR;

CREATE USER DB_VPD_SCOTT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_VPD_SCOTT;

-- RUN AS: DB_VPD
-- Create table: DB_VPD.APP_CONTEXT_USERS
CREATE TABLE DB_VPD.APP_CONTEXT_USERS (
    APP_CONTEXT_ATTR VARCHAR2(80),
    APP_CONTEXT_VALUE VARCHAR2(255),
    USER_NAME VARCHAR2(30)
)
/

-- Insert data into table: DB_VPD.APP_CONTEXT_USERS
INSERT INTO DB_VPD.APP_CONTEXT_USERS VALUES ('SECURITY_LEVEL', '1', 'DB_VPD_SCOTT');
INSERT INTO DB_VPD.APP_CONTEXT_USERS VALUES ('SECURITY_LEVEL', '2', 'DB_VPD_HR');
INSERT INTO DB_VPD.APP_CONTEXT_USERS VALUES ('SECURITY_LEVEL', '3', 'SYS');
COMMIT;

-- Create table: DB_VPD.ORDERS
CREATE TABLE DB_VPD.ORDERS (
    ORDER_ID NUMBER,
    ORDER_DATE DATE,
    CUSTOMER_ID NUMBER,
    ORDER_AMOUNT NUMBER,
    CTL_REC_STAT NUMBER
)
/

-- Insert into table: DB_VPD.ORDERS
INSERT INTO DB_VPD.ORDERS VALUES(1, SYSDATE, 200, 1203.22, 1);
INSERT INTO DB_VPD.ORDERS VALUES(2, SYSDATE, 210, 5431.23, 1);
INSERT INTO DB_VPD.ORDERS VALUES(3, SYSDATE, 212, 100023.09, 2);
INSERT INTO DB_VPD.ORDERS VALUES(4, SYSDATE, 210, 999210.55, 3);
COMMIT;
/

-- Create view: DB_VPD.ORDERS_VIEW for table: DB_VPD.ORDERS
CREATE OR REPLACE VIEW DB_VPD.ORDERS_VIEW AS  
    SELECT ORDER_ID, ORDER_DATE, CUSTOMER_ID, ORDER_AMOUNT
    FROM DB_VPD.ORDERS
    WHERE CTL_REC_STAT <= TO_NUMBER(SYS_CONTEXT('ORDERS_APP', 'SECURITY_LEVEL'))
/

-- Use view: DB_VPD.ORDERS_VIEW to see the data
SELECT * FROM DB_VPD.ORDERS_VIEW;

-- Grant SELECT privilege on view: DB_VPD.ORDERS_VIEW to user: DB_VPD_HR, DB_VPD_SCOTT, and SYS
GRANT SELECT ON DB_VPD.ORDERS_VIEW TO DB_VPD_SCOTT, DB_VPD_HR, SYS;

-- Create context for ORDERS_APP to allow the user to set the context
CREATE CONTEXT ORDERS_APP USING SYS.CONTEXT_PKG;

-- RUN AS: SYS
-- Create package: CONTEXT_PKG to set the context: ORDERS_APP
CREATE OR REPLACE PACKAGE CONTEXT_PKG AS 
    PROCEDURE SET_APP_CONTEXT(P_LEVEL VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY CONTEXT_PKG AS
    PROCEDURE SET_APP_CONTEXT(P_LEVEL VARCHAR2) IS
    BEGIN 
        DBMS_SESSION.SET_CONTEXT('ORDERS_APP', 'SECURITY_LEVEL', P_LEVEL);
    END;
END;
/

-- Grant user: DB_VPD CREATE ANY CONTEXT and EXECUTE privilege
GRANT CREATE ANY CONTEXT TO DB_VPD;
GRANT EXECUTE ON CONTEXT_PKG TO DB_VPD;

-- Create a trigger after LOGON to set context: ORDERS_APP
CREATE OR REPLACE TRIGGER TRG_DB_LOGON
AFTER LOGON 
ON DATABASE
DECLARE
    V_LEVEL VARCHAR2(255);
BEGIN
    -- DBMS_OUTPUT.PUT_LINE('#DEBUG_POINT-1');
    SELECT APP_CONTEXT_VALUE INTO V_LEVEL
    FROM DB_VPD.APP_CONTEXT_USERS
    WHERE USER_NAME = SYS_CONTEXT('USERENV', 'SESSION_USER');

    CONTEXT_PKG.SET_APP_CONTEXT(V_LEVEL);
END;
/

-- RUN AS: DB_VPD_HR, DB_VPD_SCOTT
-- Check the security level assigned
SELECT SYS_CONTEXT('ORDERS_APP', 'SECURITY_LEVEL') FROM DUAL
/

-- View the data from view: DB_VPD.ORDERS_VIEW
SELECT * FROM DB_VPD.ORDERS_VIEW;

-- RUN AS: SYS
-- Cleanup process
DROP USER DB_VPD CASCADE;
DROP USER DB_VPD_HR CASCADE;
DROP USER DB_VPD_SCOTT CASCADE;

DROP CONTEXT ORDERS_APP;

DROP PACKAGE CONTEXT_PKG;

DROP TRIGGER TRG_DB_LOGON;