-- RUN AS: SYS
-- Create the required users
CREATE USER DB_VPD IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_VPD;
GRANT ALL PRIVILEGES TO DB_VPD;

CREATE USER DB_VPD_SCOTT IDENTIFIED BY tiger;
GRANT CREATE SESSION TO DB_VPD_SCOTT;

-- RUN AS: DB_VPD
-- Create a table: DB_VPD.EMPLOYEES
CREATE TABLE DB_VPD.EMPLOYEES (
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(25) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR2(10) NOT NULL,
    SALARY NUMBER(8,2),
    MANAGER_ID NUMBER(6),
    DEPARTMENT_ID NUMBER(4),
    CTL_UPD_USER VARCHAR2(30)
)
/

-- Create a view: DB_VPD.EMPLOYEES that shows rows that belong to current user
CREATE VIEW DB_VPD.EMPLOYEES_VIEW AS 
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID, CTL_UPD_USER USER_NAME
    FROM DB_VPD.EMPLOYEES
    WHERE CTL_UPD_USER = USER
/

-- Grant SELECT and INSERT privieges on view: DB_VPD.EMPLOYEES_VIEW to user: SCOTT
GRANT SELECT, INSERT ON DB_VPD.EMPLOYEES_VIEW TO DB_VPD_SCOTT
/

-- Insert data into table: DB_VPD.EMPLOYEES using view: DB_VPD.EMPLOYEES_VIEW
INSERT INTO DB_VPD.EMPLOYEES_VIEW(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID, USER_NAME)
VALUES(100, 'SAM', 'AFYOUNI', 'SAFYOUNI', '123-234-3456', SYSDATE, 'WM_CLK', 1000, 1000, 10, USER);

COMMIT
/

-- View the data from table: DB_VPD.EMPLOYEES using view: DB_VPD.EMPLOYEES_VIEW
SELECT * FROM DB_VPD.EMPLOYEES_VIEW;

-- RUN AS: DB_VPD_SCOTT
-- Insert data using view: DB_VPD.EMPLOYEES_VIEW
INSERT INTO DB_VPD.EMPLOYEES_VIEW(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID, USER_NAME)
VALUES(101, 'JULIA', 'RONALDO', 'JRONALDO', '456-567-6789', SYSDATE, 'WM_ENG', 2000, 2000, 20, USER);

-- View data using view: DB_VPD.EMPLOYEES_VIEW
SELECT * FROM DB_VPD.EMPLOYEES_VIEW;

COMMIT;

-- RUN AS: DB_VPD
-- Create a trigger to insert user's name
CREATE OR REPLACE TRIGGER TRG_EMPLOYEES_BEFORE_INS
    BEFORE INSERT
    ON DB_VPD.EMPLOYEES
    FOR EACH ROW
BEGIN
    :NEW.CTL_UPD_USER := USER;
END;
/

-- RUN AS: DB_VPD_SCOTT
-- Insert data using view: DB_VPD.EMPLOYEES_VIEW
INSERT INTO DB_VPD.EMPLOYEES_VIEW(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID)
VALUES(103, 'PEPPER', 'POTS', 'PPOTES', '123-234-7892', SYSDATE, 'WM_SEC', 3000, 3000, 30);

-- View data using view: DB_VPD.EMPLOYEES_VIEW
SELECT * FROM DB_VPD.EMPLOYEES_VIEW;

COMMIT;