-- RUN AS: SYS
-- Create profile: PROFILE_PASSWORD_POLICY with
-- A user password cannot be reused
-- A password must expire every 15 days
-- only one login attempt is allowed.
-- with password not less then 10 char that only contains number

-- Create a password verification function
CREATE OR REPLACE FUNCTION FUNCTION_PASSWORD_VERIFY(USERNAME VARCHAR2, PASSWORD VARCHAR2, OLD_PASSWORD VARCHAR2)
RETURN BOOLEAN
IS 
BEGIN
    IF LENGTH(PASSWORD) < 10 THEN
        RETURN FALSE;
    END IF;

    FOR I IN 1..LENGTH(PASSWORD) LOOP
        IF INSTR('1234567890', SUBSTR(PASSWORD, I, 1)) = 0 THEN
            RETURN FALSE;
        END IF;
    END LOOP;

    RETURN TRUE;
END;
/

-- Create a profile: PROFILE_PASSWORD_POLICY
CREATE PROFILE PROFILE_PASSWORD_POLICY
LIMIT
    FAILED_LOGIN_ATTEMPTS 1
    PASSWORD_LIFE_TIME 15
    PASSWORD_REUSE_TIME DEFAULT
    PASSWORD_REUSE_MAX  1
    PASSWORD_LOCK_TIME DEFAULT
    PASSWORD_GRACE_TIME DEFAULT
    PASSWORD_VERIFY_FUNCTION FUNCTION_PASSWORD_VERIFY
/

-- List profile from table: DBA_PROFILES
SELECT *
FROM DBA_PROFILES
WHERE PROFILE = 'PROFILE_PASSWORD_POLICY'
/

-- If user: SAFYOUNI do not exists, create a new user: SAFYOUNI and assign a profile to user: SAFYOUNI using ALTER USER
-- Create a new user: SAFYOUNI
CREATE USER SAFYOUNI IDENTIFIED BY tiger
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 25M ON USERS
PROFILE DEFAULT
ACCOUNT UNLOCK
/

-- Grant CREATE SESSION privilege to user: SAFYOUNI to connect to DB
GRANT CREATE SESSION TO SAFYOUNI;

-- List all the users
SELECT USERNAME, PROFILE
FROM DBA_USERS
ORDER BY CREATED DESC
/

-- Assign new profile: PROFILE_PASSWORD_POLICY to user: SAFYOUNI using ALTER USER
ALTER USER SAFYOUNI
PROFILE PROFILE_PASSWORD_POLICY
/

-- Try to change the password for user: SAFYOUNI
-- Invalid Password
ALTER USER SAFYOUNI IDENTIFIED BY invalidpassword;

-- Valid Password
ALTER USER SAFYOUNI IDENTIFIED BY 1234567890;

-- Another valid password
ALTER USER SAFYOUNI IDENTIFIED BY 0123456789;

-- Try to change the password for user: SAFYOUNI to used one
ALTER USER SAFYOUNI IDENTIFIED BY 1234567890;