-- RUN AS: SYS
-- Create Application Owner: APP_OWNER
CREATE USER APP_OWNER IDENTIFIED BY tiger
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS
/

-- Grant RESOURCE, CREATE SESSION, and CREATE ROLE to user: APP_OWNER
GRANT RESOURCE, CREATE SESSION, CREATE ROLE TO APP_OWNER;
/

-- Create Proxy user: APP_PROXY
CREATE USER APP_PROXY IDENTIFIED BY tiger
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
/

-- Grant CREATE SESSION to user: APP_PROXY to connect to DB
GRANT CREATE SESSION TO APP_PROXY;
/

-- Modify user: APP_PROXY for default role as none
ALTER USER APP_PROXY DEFAULT ROLE NONE;

-- RUN AS: APP_OWNER
-- Create application tables
CREATE TABLE APP_OWNER.CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50)
);

CREATE TABLE APP_OWNER.AUTH_TABLE (
    APP_USER_ID NUMBER,
    APP_USERNAME VARCHAR2(20),
    APP_PASSWORD VARCHAR2(20),
    APP_ROLE VARCHAR2(30)
);

-- Create application roles
CREATE ROLE APP_MGR;

CREATE ROLE APP_SUP;

CREATE ROLE APP_CLERK;

-- Grant application roles to user: APP_PROXY
GRANT APP_MGR, APP_SUP, APP_CLERK TO APP_PROXY;

-- Grant SELECT, INSERT, UPDATE, and DELETE privilege to role: APP_MGR on table: APP_OWNER.CUSTOMERS
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_OWNER.CUSTOMERS TO APP_MGR;

-- Grant SELECT, INSERT, and UPDATE privilege to role: APP_SUP on table: APP_OWNER.CUSTOMERS
GRANT SELECT, INSERT, UPDATE ON APP_OWNER.CUSTOMERS TO APP_SUP;

-- Grant SELECT privilege to role: APP_CLERK on table: APP_OWNER.CUSTOMERS
GRANT SELECT ON APP_OWNER.CUSTOMERS TO APP_CLERK;

GRANT SELECT ON APP_OWNER.AUTH_TABLE TO APP_PROXY;

-- Insert data into table: APP_OWNER.CUSTOMERS
INSERT INTO APP_OWNER.CUSTOMERS
VALUES(1, 'TOM VERENDA');

INSERT INTO APP_OWNER.CUSTOMERS
VALUES(2, 'LINDA BELLA');

COMMIT;

-- Insert data into table: APP_OWNER.AUTH_TABLE
INSERT INTO APP_OWNER.AUTH_TABLE
VALUES(100, 'APP_USER_MGR', 'tiger', 'APP_MGR');

INSERT INTO APP_OWNER.AUTH_TABLE
VALUES(101, 'APP_USER_SUP', 'tiger', 'APP_SUP');

INSERT INTO APP_OWNER.AUTH_TABLE
VALUES(102, 'APP_USER_CLERK', 'tiger', 'APP_CLERK');

COMMIT;

-- Create package for login
CREATE OR REPLACE PACKAGE PKG_APP_LOGIN AUTHID CURRENT_USER IS
    FUNCTION CHECK_CREDENTIALS(V_USERNAME VARCHAR2, V_PASSWORD VARCHAR2) RETURN BOOLEAN;
    FUNCTION USER_ROLE(V_USERNAME VARCHAR2) RETURN VARCHAR2;
    PROCEDURE LOGIN(V_USERNAME VARCHAR2, V_PASSWORD VARCHAR2);
END;
/

-- Create package body for login
CREATE OR REPLACE PACKAGE BODY PKG_APP_LOGIN 
IS
    FUNCTION CHECK_CREDENTIALS(V_USERNAME VARCHAR2, V_PASSWORD VARCHAR2)
    RETURN BOOLEAN 
    IS
        V_ROW_COUNT NUMBER := 0;
    BEGIN
        SELECT COUNT(*) INTO V_ROW_COUNT 
        FROM APP_OWNER.AUTH_TABLE
        WHERE APP_USERNAME = V_USERNAME AND APP_PASSWORD = V_PASSWORD;

        IF V_ROW_COUNT = 0 THEN
            RETURN FALSE;
        END IF;

        RETURN TRUE;
    END;

    FUNCTION USER_ROLE(V_USERNAME VARCHAR2)
    RETURN VARCHAR2
    IS
        V_ROLE VARCHAR2(20);
    BEGIN
        SELECT APP_ROLE INTO V_ROLE
        FROM APP_OWNER.AUTH_TABLE
        WHERE APP_USERNAME = V_USERNAME;

        RETURN V_ROLE;
    END;

    PROCEDURE LOGIN(V_USERNAME VARCHAR2, V_PASSWORD VARCHAR2) 
    IS
        V_CORRECT_USER BOOLEAN := FALSE;
        V_APP_ROLE VARCHAR2(20);
    BEGIN
        V_CORRECT_USER := CHECK_CREDENTIALS(V_USERNAME, V_PASSWORD);

        IF V_CORRECT_USER = FALSE THEN
            DBMS_OUTPUT.PUT_LINE('LOGIN FAILED: INVALID CREDENTIALS');
            RETURN;
        END IF;

        V_APP_ROLE := USER_ROLE(V_USERNAME);

        BEGIN
            EXECUTE IMMEDIATE 'SET ROLE ' || V_APP_ROLE;
        END;
        DBMS_OUTPUT.PUT_LINE('LOGIN SUCCESSFUL: ' || V_USERNAME);
    END;
END;
/

-- Grant EXECUTE privilege to user: APP_PROXY on package: PKG_APP_LOGIN
GRANT EXECUTE ON PKG_APP_LOGIN TO APP_PROXY;

-- RUN AS: APP_PROXY
-- Login as APP_USER_MGR
BEGIN
    APP_OWNER.PKG_APP_LOGIN.LOGIN('APP_USER_MGR', 'tiger');
END;

SELECT * FROM SESSION_ROLES;

INSERT INTO APP_OWNER.CUSTOMERS
VALUES(3, 'DEVASHISH ROY');

SELECT *
FROM APP_OWNER.CUSTOMERS;

UPDATE APP_OWNER.CUSTOMERS
SET CUSTOMER_NAME = 'PIYUSH KUMAR'
WHERE CUSTOMER_ID = 3;

SELECT *
FROM APP_OWNER.CUSTOMERS
WHERE CUSTOMER_ID = 3;

DELETE FROM APP_OWNER.CUSTOMERS
WHERE CUSTOMER_ID = 3;

SELECT *
FROM APP_OWNER.CUSTOMERS;

COMMIT;

-- Login as APP_USER_SUP
BEGIN
    APP_OWNER.PKG_APP_LOGIN.LOGIN('APP_USER_SUP', 'tiger');
END;

SELECT * FROM SESSION_ROLES;

INSERT INTO APP_OWNER.CUSTOMERS
VALUES(3, 'DEVASHISH ROY');

SELECT *
FROM APP_OWNER.CUSTOMERS;

UPDATE APP_OWNER.CUSTOMERS
SET CUSTOMER_NAME = 'PIYUSH KUMAR'
WHERE CUSTOMER_ID = 3;

SELECT *
FROM APP_OWNER.CUSTOMERS
WHERE CUSTOMER_ID = 3;

DELETE FROM APP_OWNER.CUSTOMERS
WHERE CUSTOMER_ID = 3;

SELECT *
FROM APP_OWNER.CUSTOMERS;

-- Login as APP_USER_CLERK
BEGIN
    APP_OWNER.PKG_APP_LOGIN.LOGIN('APP_USER_CLERK', 'tiger');
END;

SELECT * FROM SESSION_ROLES;

INSERT INTO APP_OWNER.CUSTOMERS
VALUES(3, 'DEVASHISH ROY');

SELECT *
FROM APP_OWNER.CUSTOMERS;

UPDATE APP_OWNER.CUSTOMERS
SET CUSTOMER_NAME = 'PIYUSH KUMAR'
WHERE CUSTOMER_ID = 3;

SELECT *
FROM APP_OWNER.CUSTOMERS
WHERE CUSTOMER_ID = 3;

DELETE FROM APP_OWNER.CUSTOMERS
WHERE CUSTOMER_ID = 3;

SELECT *
FROM APP_OWNER.CUSTOMERS;

-- RUN AS: SYS
-- Cleanup process 
DROP USER APP_PROXY CASCADE;
DROP USER APP_OWNER CASCADE;
DROP ROLE APP_MGR;
DROP ROLE APP_SUP;
DROP ROLE APP_CLERK;